function [ evolutions,...
    prop_path,...
    depvar_path,...
    interp_Ascent_path,...
    interp_Descent_path,...
    DV_mapped_Ascent_path,...
    DV_mapped_Descent_path,...
    pop_path,...
    pop_i,fit_path,fit_i,output] = ...
    ...
    ...
    Path_Prep(option,p,validation,simulationDetails,...
    prop_File_Path_List_prefix,...
    depvar_File_Path_List_prefix,...
    interp_Ascent_File_Path_List_prefix,...
    interp_Decent_File_Path_List_prefix,...
    DV_mapped_Ascent_File_Path_List_prefix,...
    DV_mapped_Descent_File_Path_List_prefix,...
    Folder_Path_List,pop_file_path_prefix,fit_file_path_prefix)
%PATH_PREP Summary of this function goes here
%   Detailed explanation goes here
disp('PATH_PREP')


% Read in folder content
[ prop_Output_files,...
    n_prop_Output_files,...
    depvar_Output_files,...
    n_depvar_Output_files,...
    interp_Ascent_Output_files,...
    interp_Descent_Output_files,...
    DV_mapped_Ascent_Output_files,...
    DV_mapped_Descent_Output_files,...
    pop_files,npop_files,fit_files,nfit_files] = ...
    ...
    ...
    Read_Folder_Content(p,...
    prop_File_Path_List_prefix,...
    depvar_File_Path_List_prefix,...
    interp_Ascent_File_Path_List_prefix,...
    interp_Decent_File_Path_List_prefix,...
    DV_mapped_Ascent_File_Path_List_prefix,...
    DV_mapped_Descent_File_Path_List_prefix,...
    pop_file_path_prefix,fit_file_path_prefix);

% Construct all file paths to evaluate
[ prop_path,...
    depvar_path,...
    interp_Ascent_path,...
    interp_Descent_path,...
    DV_mapped_Ascent_path,...
    DV_mapped_Descent_path,...
    pop_path,pop_i,fit_path,fit_i] = ...
    ...
    ...
    Contruct_File_Paths(...
    prop_Output_files,...
    n_prop_Output_files,...
    depvar_Output_files,...
    n_depvar_Output_files,...
    interp_Ascent_Output_files,...
    interp_Descent_Output_files,...
    DV_mapped_Ascent_Output_files,...
    DV_mapped_Descent_Output_files,...
    pop_files,...
    npop_files,...
    fit_files,...
    nfit_files);

% Load lists of analyzed simulations and determine remaining paths to analyze
[evolutions,output] = Load_Data(option,p,validation,simulationDetails,Folder_Path_List,npop_files );

% Determine if all paths have been analyzed. If so, then plot and got to next folder.
%idx = idx(~isnan(idx));



end

